# `get_rec_item` Function

If the recs are item clusters and you want to get actual items, use this!

In [24]:
import numpy as np
import pandas as pd

from random_gen import *
from get_rec import *

def get_rec_item(df_rec, top_k, ic_assignment):
    
    """Returns the top K item recommendations for each user in the user list. 
    Items are selected randomly from the top recommended item cluster, exhaustively. Left overs are taken from the next highest ranked item clusters in a cascading fashion.
    
            Parameters:
                    df_rec (pandas.DataFrame): Table containing the top N item cluster recommendations for each user in the user list
                    ic_assignment (array-like): List containing the cluster assignment of each item
                    top_n (int): Number of items to recommend

            Returns:
                    df_rec_item (pandas.DataFrame): Table containing the top K item recommendations for each user in the user list
                    
    """

    # Create recommendation table
    df_rec_item = pd.DataFrame()
    df_rec_item['user_id'] = df_rec['user_id']
    
    for i in range(top_k):
        df_rec_item['rank_'+str(i+1)] = np.zeros(df_rec_item.shape[0])
        
    #for j in range(df_rec_item.shape[0]):
    #    df_rec_item.iloc[j, i+1] = 
                
    return df_rec_item

## Example

In [25]:
n_user = 100
n_item = 50
sample_size = 10
n_user_cluster = 5
n_item_cluster = 5
top_n = 3
random_seed = 1

user_id_list = list(range(n_user))
user_list = random_user_list(n_user, sample_size, random_seed)
uc_assignment = random_user_cluster(n_user, n_user_cluster, random_seed)
utility_matrix_o, utility_matrix = random_utility_matrix(n_user_cluster, n_item_cluster, random_seed)
df_rec = get_rec(utility_matrix, utility_matrix_o, user_list, top_n, uc_assignment)
df_rec

user_id  rank_1  rank_2  rank_3
0       80     1.0     2.0     4.0
1       84     3.0     4.0     1.0
2       33     3.0     4.0     1.0
3       81     0.0     3.0     1.0
4       93     3.0     1.0     0.0
5       17     0.0     3.0     1.0
6       36     3.0     1.0     0.0
7       82     1.0     2.0     4.0
8       69     4.0     2.0     0.0
9       65     3.0     1.0     0.0

In [26]:
ic_assignment = random_user_cluster(n_item, n_item_cluster, random_seed=2)
ic_assignment

array([0, 0, 3, 2, 3, 0, 2, 1, 3, 2, 4, 4, 4, 3, 4, 2, 3, 3, 2, 1, 2, 4,
       3, 0, 4, 3, 1, 2, 0, 4, 4, 2, 4, 2, 1, 0, 2, 2, 1, 0, 1, 0, 2, 1,
       1, 1, 4, 2, 3, 0])

In [50]:
top_k = 10

# Create recommendation table
df_rec_item = pd.DataFrame()
df_rec_item['user_id'] = df_rec['user_id']

for i in range(top_k):
    df_rec_item['rank_'+str(i+1)] = np.zeros(df_rec_item.shape[0])

for j in range(df_rec_item.shape[0]):
    item_rec = []
    rank = 0
    while len(item_rec) < top_k:
        item_list = np.where(ic_assignment == df_rec.iloc[j, rank+1])[0]
        if top_k-len(item_rec) > len(item_list):
            item_rec = item_rec + list(item_list)
        else:
            item_rec = item_rec + list(np.random.choice(item_list, size=top_k-len(item_rec), replace=False))
    df_rec_item.iloc[j] = item_rec

df_rec_item

[ 7 19 26 34 38 40 43 44 45]
[7, 19, 26, 34, 38, 40, 43, 44, 45]
---
[ 2  4  8 13 16 17 22 25 48]
[2, 4, 8, 13, 16, 17, 22, 25, 48]
---
[ 2  4  8 13 16 17 22 25 48]
[2, 4, 8, 13, 16, 17, 22, 25, 48]
---
[ 0  1  5 23 28 35 39 41 49]
[0, 1, 5, 23, 28, 35, 39, 41, 49]
---
[ 2  4  8 13 16 17 22 25 48]
[2, 4, 8, 13, 16, 17, 22, 25, 48]
---
[ 0  1  5 23 28 35 39 41 49]
[0, 1, 5, 23, 28, 35, 39, 41, 49]
---
[ 2  4  8 13 16 17 22 25 48]
[2, 4, 8, 13, 16, 17, 22, 25, 48]
---
[ 7 19 26 34 38 40 43 44 45]
[7, 19, 26, 34, 38, 40, 43, 44, 45]
---
[10 11 12 14 21 24 29 30 32 46]
[]
---
[ 2  4  8 13 16 17 22 25 48]
[2, 4, 8, 13, 16, 17, 22, 25, 48]
---


user_id  rank_1  rank_2  rank_3  rank_4  rank_5  rank_6  rank_7  rank_8  \
0       80     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1       84     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2       33     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3       81     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4       93     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5       17     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
6       36     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
7       82     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
8       69     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
9       65     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

   rank_9  rank_10  
0     0.0      0.0  
1     0.0      0.0  
2     0.0      0.0  
3     0.0      0.0  
4     0.0      0.0  
5     0.0      0.0  
6     0.0      0.0  
7     0.0      0.0  
8     0.0      0.0  
9     0.0      0.0